### ISSUE TITLE
 Permission denied (publickey)

### ISSUE THREAD

**Issue by Artificial-dev** [deepjyoti30/ytmdl-web-v2#78]
root@ubunti:/home/youtube# git clone git@github.com:deepjyoti30/ytmdl-web-v2 && npm i && npm run build
Cloning into 'ytmdl-web-v2'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by deepjyoti30** [comment]
@Artificial-dev are you sure this is not a problem at your end? Are you able to clone other repos?

This repo is public and I don't think the issue you have reported is from the repo's end. Might be some configuration that you are missing.

**Comment by Artificial-dev** [comment]
> @Artificial-dev are you sure this is not a problem at your end? Are you able to clone other repos?
> 
> This repo is public and I don't think the issue you have reported is from the repo's end. Might be some configuration that you are missing.

**Comment by Artificial-dev** [comment]
Yes , no problem in cloning repod.
Are any configuration to make in repo ?
I don't understand this line "git@github.com: Permission denied (publickey)."

**Comment by deepjyoti30** [comment]
> I don't understand this line "[git@github.com](mailto:git@github.com): Permission denied (publickey)."

This line is indicating that something with wrong with the `git clone` command.

Try this:

```sh
git clone [git@github.com](mailto:git@github.com):deepjyoti30/ytmdl-web-v2
```

As I said, the permission denied error is from this command so you will see the error. The error is indicating that something with your git config is not correct. As an alternative, you can try cloning using the github url:

```sh
git clone https://github.com/deepjyoti30/ytmdl-web-v2
```

After that you can run the rest of the commands:

```sh
cd ytmdl-web-v2 && npm i && npm run build
```

> NOTE that you were not doing the `cd` step which would have let to the `npm i` command throwing an error but I am sure that the error you have reported is from the git clone command.

**Comment by Artificial-dev** [comment]
OK ! WE SOVLED THIS ERROR
The problem gitclone as you said but there one more problem with " npm i && npm run build"


npm i && npm run serve

up to date, audited 1690 packages in 15s

5 packages are looking for funding
  run `npm fund` for details

65 vulnerabilities (1 low, 30 moderate, 27 high, 7 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> ytmdl-web-v2@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...ytmdl-web-v2/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:471:10)
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:503:5
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:358:12
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/data/data/com.termux/files/ytmdl-web-v2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:471:10)
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:503:5
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/webpack/lib/NormalModule.js:358:12
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/data/data/com.termux/files/ytmdl-web-v2/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/data/data/com.termux/files/ytmdl-web-v2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /data/data/com.termux/files/ytmdl-web-v2/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.2.0
